{
 "title": "monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Calculator Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "errors_calculator_total{}" }
   ]
  },
  {
   "title": "Last Values",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_calculator{}", "legendFormat": "calc" },
    { "expr": "last_sum1n{}", "legendFormat": "sum" },
    { "expr": "last_fibo{}", "legendFormat": "fibo" },
    { "expr": "list_size{}", "legendFormat": "list" }
   ]
  },
  {
   "title": "HTTP average duration",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_milliseconds_sum{}"
    }
   ]
  },
  {
   "title": "HTTP requests per route",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_requests_total{}" }
   ]
  }
 ]
}